apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: datamanipulator-spark-application
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "localhost:5001/datamanipulator:0.0.1"
  imagePullPolicy: Always
  mainClass: com.arcadia.datamanipulator.MainApplication
  mainApplicationFile: "local:///opt/spark/jars/datamanipulator-assembly-0.0.1.jar"
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
