apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-application-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - "sparkoperator.k8s.io"
  resources:
  - sparkapplications
  - sparkapplications/finalizers
  verbs:
  - '*'